import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className="min-h-screen flex flex-col">
        {/* Toaster  */}
        <header className="border-b sticky top-0 bg-white z-50">
          <Header/>
          {/* Header */}

          </header> 
          <div className="bg-[#F4F2ED] flex-l w-full">
            <main>{children}</main>
            </div> 
      </body>
    </html>
    </ClerkProvider>
  );
}
